version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      # Batch minor/patch GitHub Actions into a single PR.
      gha-bump:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"