# Use new trusty images, should yield newer compilers and packages
dist: trusty
sudo: false
language: cpp

# skip the install step, we have no dependencies
install: true

# set up build directories for Release and Debug builds and run cmake in each; "make" should then work
# note that we start out in /home/travis/build/MesserLab/SLiM here, and end in /home/travis/build/MesserLab
before_script:
  - cd ..
  - mkdir Release
  - cd Release
  - cmake -D CMAKE_BUILD_TYPE=Release ../SLiM
  - cd ..
  - mkdir Debug
  - cd Debug
  - cmake -D CMAKE_BUILD_TYPE=Debug ../SLiM
  - cd ..

# build using make, then run Eidos and SLiM tests; do for each of Release and Debug
# builds can take more than 10 minutes so we use travis_wait
script:
  - cd Release
  - travis_wait make
  - ./eidos -testEidos
  - ./slim -testEidos
  - ./slim -testSLiM
  - cd ../Debug
  - travis_wait make
  - ./eidos -testEidos
  - ./slim -testEidos
  - ./slim -testSLiM

# use gcc; this probably doesn't matter since we call make anyway
# it would be nice to try different gcc versions, but that is presently quite complex
# see https://stackoverflow.com/questions/29312015/building-with-more-than-one-version-of-a-compiler
# see https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
compiler:
  - gcc

# linux and os x builds
os:
  - linux
  - osx

# test only the master branch for now; add other branches as needed
branches:
  only:
    - master
    - openmp

# notify me by email after all builds
#notifications
notifications:
  email:
    on_success: always
    on_failure: always
